\c afro_link;

INSERT INTO types(type_name) VALUES
 ('Home Decor'),
 ('Arts & Culture'),
 ('Gifts & Beyond'),
 ('Beauty'),
 ('Health & Fitness'),
 ('Literature'),
 ('Clothing & Accessories'),
 ('Food & Drink'),
 ('Education & Career');
 
INSERT INTO businesses(biz_name,hours) VALUES
 ('228 Grant Street Candle Co.','online business')
,('AphroChic','online business')
,('The Black Home','online business')
,('Black Pepper Paperie Co.','online business')
,('Bolé Road Textiles','online business')
,('Clare','Mon - Fri, 9am - 9pm 
Sat - Sun, 9am - 5pm')
,('Claude Home','online business')
,('Effortless Composition','online business')
,('Goodee','online business')
,('Ilé Ilà','online business')
,('Jungalow','online business')
,('Lichen','Sat - Sun, 12pm - 5pm
Mon, Closed or By Appointment
Tue, Closed or By Appointment
Wed, 12pm - 5pm
Thur, Closed or By Appointment
Fri, Closed or By Appointment')
,('Linoto','online business')
,('Lit Bklyn','online business')
,('Malene B','online business')
,('Marie Burgos Collection','online business')
,('Natty Garden','All Week, 10am - 6pm')
,('Peace & Riot','Tue - Fri, 11am - 6pm 
Sat, 10am - 7pm 
Sun, 11am - 6pm')
,('Pottery by Osa','online business')
,('Robin Wilson Home','Available during weekday business hours, but we are typically off-site focused on client projects')
,('Rochelle Porter','online business')
,('See Line Ceramics','online business')
,('Sheila Bridges','online business')
,('SustainAble Home Goods','online business')
,('Tackussanu Senegal','online business')
,('Tactile Matter','online business')
,('xN Studio','online business')
,('Yowie','online business')
,('Elias Williams','online business')
,('Elliot Jerome Brown Jr','online business')
,('JOIRI MINAYA','online business')
,('Groana Melendez','online business')
,('MIRANDA BARNES','online business')
,('Bold Xchange','online business')
,('Celsious','Tue - Fri, 11am - 7pm
Sat - Mon, 8am - 4pm')
,('Custom Collaborative','')
,('Manual','online business')
,('Marché Rue Dix','Mon - Sat, 12pm - 9pm, 
Sun, 11am - 8pm')
,('Neighborhood Fiber Co.','')
,('Reparations Club','online business')
,('String Thing Studio','')
,('BeautyStat Cosmetics','online business')
,('Beneath Your Mask','online business')
,('BLK + GRN','online business')
,('Briogeo','available at birchbox.com')
,('Golde','online business')
,('Hanahana Beauty','online business')
,('Haus Urban','online business')
,('Highbrow Hippie','online business')
,('The Honey Pot','available at drug stores')
,('Hyper Skin','online business')
,('Lauren Napier Beauty','online business')
,('OUI The People','online business')
,('Pat McGrath Labs','available at sephora.com')
,('People of Color Beauty','online business')
,('Unsun','online business')
,('Uoma Beauty','online business')
,('Zambo Aroma','7 days, 1pm - 9pm')
,('Ailey Extension','7 days, 8am – 11pm')
,('Black Girls Run','online business')
,('Body Space Fitness','')
,('Grillz and Granola','online business')
,('HealHaus','Mon-Fri,   7am – 7:30pm
Sat-Sun,   8am – 7:30pm')
,('Iconoclast Fitness','Mon - Fri, 6am – 9pm
Sat - Sun 8am – 2pm')
,('The Underbelly','online business')
,('Mind Body Soul','online business')
,('Cafe con Libros','Tues-Fri, 9am - 1pm
Sat & Sun, 9am - 3pm')
,('Frugal Bookstore','online business')
,('Harriett’s Bookshop','online business')
,('For Keeps Books','online business')
,('Fulton Street Books and Coffee','online business')
,('The Lit. Bar','')
,('Loving Me Books','online business')
,('Mahogany Books','online business')
,('Semicolon Bookstore and Gallery','online business')
,('Sister’s Uptown Bookstore','Wed, Fri 1PM - 5PM,
Sat, 1PM - 5PM,
Sun, Closed')
,('Source of Knowledge','temporarily closed')
,('Anya Lust','online business')
,('Baby Phat','online business')
,('BedStuyFly','')
,('BLK MKT Vintage','online business')
,('Brooklyn Circus','')
,('Brother Vellies','')
,('Cameron Tea','online business')
,('Castamira','online business')
,('CBAAF','online business')
,('Christopher John Rogers','online business')
,('Cool and Casual Studios','online business')
,('Cushnie','online business')
,('Diop','online business')
,('Edas','online business')
,('Flat Fifteen','online business')
,('Gizmo Vintage Honey','Wed-Sun 12 -6')
,('Golden Girly','online business')
,('House of Aama','online business')
,('KAI','online business')
,('Kenneth Ize','online business')
,('Kutula by Africana','online business')
,('LaQuan Smith','online business')
,('Local European','online business')
,('Madame Matovu Vintage','')
,('Maki Oh','online business')
,('Moshood Creations','')
,('Nandi Naya','online business')
,('Nude Barre','available at mulberry-grand.com')
,('Octave Jewelry','online business')
,('Oma the Label','online business')
,('Onion Cut & Sewn','online business')
,('Orange Culture','')
,('Peju Obasa','')
,('Post-Imperial','')
,('Rebecca Allen','visit by appt')
,('Riot Swim','')
,('Sincerely, Tommy','8am — 6pm daily, 
8am — 4pm
5pm — 10pm daily')
,('The Sixes','online business')
,('Slashed by Tia','online business')
,('Small Needs','online business')
,('T.A.','')
,('Telfar','online business')
,('TLZ L’FEMME','online business')
,('Tree Fairfax','online business')
,('Victor Glemaud','online business')
,('Wales Bonner','online business')
,('Yam','online business')
,('Zou Xou Shoes','online business')
,('C.L.U.E','online business')
,('A Dozen Cousins','online business')
,('Alibi Lounge','')
,('Alvin & Friends','Mon, CLOSED
Tue, Wed, Sun, 5pm - 9pm
Thu, 5pm - 10pm
Fri, Sat 5pm - 11pm
BAR open until 1am
OPEN for BRUNCH Sat 11:30am - 2pm
OPEN for BRUNCH Sun 11:30am - 3:30pm')
,('Basbaas Foods','online business')
,('Benyam','Mon, CLOSED
Tue, CLOSED
Wed, 4pm – 9pm
Thu, 4pm – 9pm
Fri, 12pm – 9pm
Sat, 12pm – 9pm
Sun, 12pm – 8pm"')
,('Blu The Baker','online business')
,('BLVD Bistro','Thu - Fri, 12pm - 6pm
Sat - Sun, 10am – 6pm
Mon - Wed, CLOSED')
,('Blk & Bold','available at target.com')
,('Brooklyn Chop House','')
,('Brooklyn Tea','7 days, 8am- 6pm')
,('Casa Del Toro','Mon-Thu, 5pm - 11pm
Fri-Sat, 5pm - 1am
Sun, 5pm - 10pm')
,('Charles’ Pan Fried Chicken','Mon - Sun, 1 - 10pm')
,('Chocolat','')
,('Cremas Absalon','online business')
,('Global Village Cuisine','online business')
,('Harlem Hops','7 days, 2pm – 8pm')
,('Harvest And Revel','catering service')
,('Jolo''s Kitchen','Weekdays 11:30am - 8pm, Weekends 1pm - 8pm')
,('Jones Bar-B-Q','online business')
,('Juices for Life (Castle Hill – Bronx)','')
,('Justice of the Pies','online business')
,('Lillie’s of Charleston','online business')
,('Lolo''s Seafood Shack','Mon, CLOSED, 
Tue - Sun, 12pm - 9pm')
,('Maison Noir Wines','online business')
,('Mikey Likes It East Village','online business')
,('Nature Sings','online business')
,('Negril Village NYC','online business')
,('On The Hunt','online business')
,('Pastry Art by Evelyn R. Cooke','online business')
,('Pepe''s Place','Mon - Tues, CLOSED
Wed - Sun 1pm - 8pm')
,('Red Bay Coffee','online business')
,('Ripe Kitchen & Bar','Tue - Thu, 4pm - 11:30pm 
Fri - Sat, 4pm - 12:30am 
Sun, 4pm - 10:30pm 
Mon, CLOSED')
,('Roc N Ramen','7 days, 12pm - 8pm')
,('Salut Nutrition','online business')
,('Seasoned Vegan','Wed, Thu, Fri, 5pm - 10pm 
Sat, 1pm - 10pm
Sun, 4pm -9pm 
Mon, Tue, CLOSED')
,('The Sip','online business')
,('Sol Cacao','available in specialty food stores')
,('Sol Sips','Wed - Sat, 12pm - 7pm, 
Mon, Tues, Sun, CLOSED')
,('Whetstone Magazine','online business')
,('Tings Jamaican Jerk Chicken','available at Chelsea Market, 
Main Concourse,
Mon-Sun, 11:00 AM - 8:30 PM')
,('Zafa Wines','online business')
,('Black Tech Pipeline','online business')
,('I DON’T DO CLUBS(IDDC)','online business');

INSERT INTO owners(owner_id,owner_name) VALUES
 (1,NULL)
,(2,'Jeanine Hays and Bryan Mason')
,(3,'Neffi Walker')
,(4,'Hadiya Williams')
,(5,'Hana Getachew')
,(6,'Nicole Gibbons')
,(7,NULL)
,(8,'Brittiny Terry')
,(9,'Byron and Dexter Peart')
,(10,'Tosin Oshinowo')
,(11,'Justina Blakeney')
,(12,'Ed Be & Jared Blake')
,(13,'Jason Evege')
,(14,'Denequa Williams')
,(15,'Malene Barnett')
,(16,'Marie Burgos')
,(17,'Joel Mahfood')
,(18,'Achuziam Maha-Sanchez')
,(19,'Osa Atoe')
,(20,'Robin Wilson')
,(21,'Rochelle Porter')
,(22,'Nikita Richardson')
,(23,'Sheila Bridges')
,(24,'LaToya Tucciarone')
,(25,NULL)
,(26,'Kenesha Sneed')
,(27,'Nasozi Kakembo')
,(28,'Shannon Maldonado')
,(29,'Elias Williams')
,(30,'Elliot Jerome Brown Jr')
,(31,'Joiri Minaya')
,(32,'Groana Melendez')
,(33,'Miranda Barnes')
,(34,'Danielle Deavens and Doug Spencer')
,(35,'Corinna and Theresa Williams')
,(36,NULL)
,(37,'Malcolm Dia')
,(38,NULL)
,(39,'Karida Collins')
,(40,'Jazzi McGilbert')
,(41,'Felicia Eve')
,(42,'Ron Robinson')
,(43,'Dana Jackson')
,(44,NULL)
,(45,'Nancy Twine')
,(46,'Trinity Mouzon Wofford')
,(47,'Abena Boamah-Acheampong')
,(48,'Hassan Sayyed')
,(49,'Myka Harris and Kadi Lee')
,(50,'Bea Dixon')
,(51,'Desiree Verdejo')
,(52,'Lauren Napier')
,(53,'Karen Young')
,(54,'Pat McGrath')
,(55,'Jacqueline Carrington')
,(56,'Katonya Breaux')
,(57,'Sharon Chuter,')
,(58,NULL)
,(59,NULL)
,(60,NULL)
,(61,NULL)
,(62,'Chavonne Hodges')
,(63,'Darian Hall and Elisa Shankle')
,(64,'Ngo Okafor')
,(65,'Jessamyn Stanley')
,(66,'Andrea Marie')
,(67,NULL)
,(68,NULL)
,(69,NULL)
,(70,NULL)
,(71,NULL)
,(72,NULL)
,(73,'Angela Nesbitt')
,(74,NULL)
,(75,NULL)
,(76,'Janifer Wilson and daughter Kori')
,(77,NULL)
,(78,'Krystle Kotara')
,(79,'Kimora Lee Simmons')
,(80,NULL)
,(81,'Jannah Handy and Kiyanna Stewart')
,(82,'Ouigi Theodore')
,(83,'Aurora James')
,(84,NULL)
,(85,'Chantel Davis')
,(86,NULL)
,(87,'Christopher John Rogers')
,(88,NULL)
,(89,'Carly Cushnie')
,(90,NULL)
,(91,'Sade Mims')
,(92,'Francesca Kappo')
,(93,NULL)
,(94,NULL)
,(95,'Rebecca Henry and Akua Shabaka')
,(96,'Fisayo Longe')
,(97,'Kenneth Ize')
,(98,NULL)
,(99,'LaQuan Smith')
,(100,'Alexandra Bunch')
,(101,'Rosemary Matovu')
,(102,'Maki Osakwe')
,(103,'Moshood Afariogun')
,(104,'Hleziphansi Zita')
,(105,'Erin Carpenter')
,(106,NULL)
,(107,NULL)
,(108,'Whitney Mero')
,(109,'Adebayo Oke-Lawal')
,(110,'Peju Obasa')
,(111,'Niyi Okuboyejo')
,(112,'Rebecca Allen')
,(113,'Monti Landers')
,(114,'Kai Avent-deLeon')
,(115,'Franci Girard')
,(116,'Tia Adeola')
,(117,NULL)
,(118,'Telsha Anderson')
,(119,'Telfar Clemens')
,(120,NULL)
,(121,NULL)
,(122,'Victor Glemaud')
,(123,'Wales Bonner')
,(124,'Morgan Thomas')
,(125,'Katherine Theobalds')
,(126,'Anthony Telesford')
,(127,NULL)
,(128,NULL)
,(129,NULL)
,(130,'Hawa Hassan')
,(131,NULL)
,(132,NULL)
,(133,NULL)
,(134,'Pernell Cezar and Rod Johnson')
,(135,NULL)
,(136,NULL)
,(137,NULL)
,(138,NULL)
,(139,NULL)
,(140,NULL)
,(141,NULL)
,(142,NULL)
,(143,NULL)
,(144,'Marc A. Moise (Jolo)')
,(145,'Deborah “Little” Jones and Mary “Shorty” Jones')
,(146,NULL)
,(147,'Maya-Camille Broussard')
,(148,NULL)
,(149,NULL)
,(150,'André Hueston Mack')
,(151,NULL)
,(152,NULL)
,(153,NULL)
,(154,NULL)
,(155,NULL)
,(156,NULL)
,(157,'Keba Konte')
,(158,NULL)
,(159,'Chef Wayne Carrington')
,(160,NULL)
,(161,NULL)
,(162,'Catherine Carter and Erica Davis')
,(163,NULL)
,(164,'Francesca Chaney')
,(165,'Stephen Satterfield')
,(166,NULL)
,(167,'Krista Scruggs')
,(168,'Pariss Athena')
,(169,'Genese Jamilah');

INSERT INTO categories(biz_id,type_id) VALUES
 (1,1)
,(2,1)
,(3,1)
,(4,1)
,(5,1)
,(6,1)
,(7,1)
,(8,1)
,(9,1)
,(10,1)
,(11,1)
,(12,1)
,(13,1)
,(14,1)
,(15,1)
,(16,1)
,(17,1)
,(18,1)
,(19,1)
,(20,1)
,(21,1)
,(22,1)
,(23,1)
,(24,1)
,(25,1)
,(26,1)
,(27,1)
,(28,1)
,(29,2)
,(30,2)
,(31,2)
,(32,2)
,(33,2)
,(34,3)
,(35,3)
,(36,3)
,(37,3)
,(38,3)
,(39,3)
,(40,3)
,(41,3)
,(42,4)
,(43,4)
,(44,4)
,(45,4)
,(46,4)
,(47,4)
,(48,4)
,(49,4)
,(50,4)
,(51,4)
,(52,4)
,(53,4)
,(54,4)
,(55,4)
,(56,4)
,(57,4)
,(58,4)
,(59,5)
,(60,5)
,(61,5)
,(62,5)
,(63,5)
,(64,5)
,(65,5)
,(66,5)
,(67,6)
,(68,6)
,(69,6)
,(70,6)
,(71,6)
,(72,6)
,(73,6)
,(74,6)
,(75,6)
,(76,6)
,(77,6)
,(78,7)
,(79,7)
,(80,7)
,(81,7)
,(82,7)
,(83,7)
,(84,7)
,(85,7)
,(86,7)
,(87,7)
,(88,7)
,(89,7)
,(90,7)
,(91,7)
,(92,7)
,(93,7)
,(94,7)
,(95,7)
,(96,7)
,(97,7)
,(98,7)
,(99,7)
,(100,7)
,(101,7)
,(102,7)
,(103,7)
,(104,7)
,(105,7)
,(106,7)
,(107,7)
,(108,7)
,(109,7)
,(110,7)
,(111,7)
,(112,7)
,(113,7)
,(114,7)
,(115,7)
,(116,7)
,(117,7)
,(118,7)
,(119,7)
,(120,7)
,(121,7)
,(122,7)
,(123,7)
,(124,7)
,(125,7)
,(126,7)
,(127,8)
,(128,8)
,(129,8)
,(130,8)
,(131,8)
,(132,8)
,(133,8)
,(134,8)
,(135,8)
,(136,8)
,(137,8)
,(138,8)
,(139,8)
,(140,8)
,(141,8)
,(142,8)
,(143,8)
,(144,8)
,(145,8)
,(146,8)
,(147,8)
,(148,8)
,(149,8)
,(150,8)
,(151,8)
,(152,8)
,(153,8)
,(154,8)
,(155,8)
,(156,8)
,(157,8)
,(158,8)
,(159,8)
,(160,8)
,(161,8)
,(162,8)
,(163,8)
,(164,8)
,(165,8)
,(166,8)
,(167,8)
,(168,9)
,(169,9);

INSERT INTO contacts(contact_id,phone,email,social_media) VALUES
 (1,NULL,NULL,'https://www.instagram.com/228grantstreet/')
,(2,NULL,NULL,'https://www.instagram.com/aphrochic/?hl=en')
,(3,NULL,NULL,'https://www.instagram.com/theblackhomedesign/?hl=en')
,(4,NULL,NULL,'https://www.instagram.com/blackpepperpaperieco/')
,(5,'6468203794',NULL,'https://www.instagram.com/boleroadtextiles/?hl=en')
,(6,NULL,NULL,'https://www.instagram.com/clarepaint/?hl=en')
,(7,NULL,NULL,'https://www.instagram.com/claudehome/')
,(8,NULL,NULL,'https://www.instagram.com/effortlesscomposition/')
,(9,NULL,NULL,'https://www.instagram.com/goodeeworld/?hl=en')
,(10,NULL,NULL,'https://www.instagram.com/ile.ila/?hl=en')
,(11,NULL,NULL,'https://www.instagram.com/thejungalow/?hl=en')
,(12,NULL,NULL,'https://www.instagram.com/lichennyc/?hl=en')
,(13,'8889546686',NULL,'https://www.instagram.com/linotodotcom/?hl=en')
,(14,NULL,NULL,'https://www.instagram.com/litbklyn/?hl=en')
,(15,NULL,NULL,'https://www.instagram.com/maleneblifestyle/?hl=en')
,(16,'9173539149',NULL,'https://www.instagram.com/marieburgos.design/?hl=en')
,(17,'7184838833',NULL,'https://www.instagram.com/nattygarden/?hl=en')
,(18,NULL,NULL,'https://www.instagram.com/peaceandriot/')
,(19,NULL,NULL,'https://www.instagram.com/potterybyosa/?hl=en')
,(20,'8008303874',NULL,'https://www.instagram.com/robinwilsonhome/?hl=en')
,(21,NULL,NULL,'https://www.instagram.com/roporterdesign/?hl=en')
,(22,NULL,NULL,'https://www.instagram.com/seelineceramics/')
,(23,'2126786872',NULL,'https://www.instagram.com/harlemtoilegirl/?hl=en')
,(24,NULL,NULL,'https://www.instagram.com/sustainablehomegoods/?hl=en')
,(25,'7707276794',NULL,'https://www.instagram.com/tackussanu_senegal/')
,(26,NULL,NULL,'https://www.instagram.com/tactilematter/?hl=en')
,(27,NULL,NULL,'https://www.instagram.com/xnstudio_/?hl=en')
,(28,NULL,NULL,'https://www.instagram.com/helloyowie/')
,(29,NULL,'info@eliaswilliams.com','https://www.instagram.com/elias.williams/')
,(30,NULL,'elliottbrownjr@gmail.com','https://www.instagram.com/elliottjeromebrownjr/')
,(31,NULL,'joiriminaya@gmail.com','https://www.instagram.com/joiriminaya/')
,(32,'6465044762','contact@groanamelendez.com','https://www.instagram.com/groana/')
,(33,NULL,'mirandaRbarnes@gmail.com','https://www.instagram.com/mirandabarnes/?hl=en')
,(34,NULL,NULL,'https://www.instagram.com/bold_xchange/?hl=en')
,(35,NULL,NULL,'https://www.instagram.com/celsious_social/?hl=en')
,(36,'6465968005','info@customcollaborative.org','https://www.instagram.com/customcolab/?hl=en')
,(37,NULL,NULL,'https://www.instagram.com/manual_nyc/?hl=en')
,(38,'3474145436','marcheruedix@gmailcom','https://www.instagram.com/marcheruedix/?hl=en')
,(39,NULL,NULL,'https://www.instagram.com/neighborhoodfiberco/?hl=en')
,(40,'3235910012',NULL,'https://www.instagram.com/reparations.club/?hl=en')
,(41,'9293376130','E. hello@stringthingstudio.com','https://www.instagram.com/stringthingstudio/?hl=en')
,(42,NULL,NULL,'https://www.instagram.com/beautystat/?hl=en')
,(43,NULL,NULL,'https://www.instagram.com/beneathyourmask/')
,(44,NULL,NULL,'https://www.instagram.com/blkandgrn/')
,(45,NULL,NULL,'https://www.instagram.com/briogeo/?hl=en')
,(46,NULL,NULL,'https://www.instagram.com/golde/?hl=en')
,(47,NULL,NULL,'https://www.instagram.com/hanahana_beauty/?hl=en')
,(48,NULL,NULL,'https://www.instagram.com/hausurban/?hl=en')
,(49,NULL,NULL,'https://www.instagram.com/highbrowhippie/?hl=en')
,(50,NULL,NULL,'https://www.instagram.com/thehoneypotco/?hl=en')
,(51,NULL,NULL,'https://www.instagram.com/gethyperskin/?hl=en')
,(52,NULL,NULL,'https://www.instagram.com/laurennapierbeauty/?hl=en')
,(53,NULL,NULL,'https://www.instagram.com/ouithepeople/?hl=en')
,(54,NULL,NULL,'https://www.instagram.com/patmcgrathreal/?hl=en')
,(55,NULL,NULL,'https://www.instagram.com/peopleofcolorbeauty/?hl=en')
,(56,NULL,NULL,'https://www.instagram.com/unsuncosmetics/?hl=en')
,(57,NULL,NULL,'https://www.instagram.com/uomabeauty/')
,(58,'3473468707',NULL,'https://www.instagram.com/zamboaroma/')
,(59,'2124059000',NULL,'https://www.instagram.com/aileyextension/?hl=en')
,(60,NULL,NULL,'https://www.instagram.com/officialblackgirlsrun/?hl=en')
,(61,'6466844912',NULL,'https://www.instagram.com/bodyspacenyc/?hl=en')
,(62,NULL,NULL,'https://www.instagram.com/grillzandgranola/?hl=en')
,(63,'3474137774',NULL,'https://www.instagram.com/healhaus/?hl=en')
,(64,'6465984806',NULL,'https://www.instagram.com/iconoclastnyc/?hl=en')
,(65,NULL,NULL,'https://www.instagram.com/theunderbellyyoga/?hl=en')
,(66,NULL,NULL,'https://www.instagram.com/andreamindbodysoul/')
,(67,'3474602838','info@cafeconlibrosbk.com','https://www.instagram.com/cafeconlibros_bk/?hl=en')
,(68,NULL,NULL,'https://www.instagram.com/frugalbooks/?hl=en')
,(69,NULL,NULL,'https://www.instagram.com/harrietts_bookshop/?hl=en')
,(70,NULL,NULL,'https://www.instagram.com/forkeepsbooks/?hl=en')
,(71,NULL,NULL,'https://www.instagram.com/fultonstreet918/')
,(72,NULL,NULL,'https://www.instagram.com/thelitbar/?hl=en')
,(73,NULL,NULL,'https://www.instagram.com/lovingmebooks/')
,(74,NULL,NULL,'https://www.instagram.com/mahoganybooks/')
,(75,NULL,NULL,'https://www.instagram.com/semicolonchi/')
,(76,'2128623680','info@sistersuptownbookstore.com','https://www.instagram.com/sistersuptown/')
,(77,NULL,NULL,'https://www.instagram.com/sourceofknowledge/')
,(78,NULL,NULL,'https://www.instagram.com/anya_lust/?hl=en')
,(79,NULL,NULL,'https://www.instagram.com/babyphat/?hl=en')
,(80,'7185763183,
3474069927',NULL,'https://www.instagram.com/bedstuyfly/?hl=en')
,(81,NULL,NULL,'https://www.instagram.com/blkmktvintage/?hl=en')
,(82,NULL,'ny@thebkcircus.com','https://www.instagram.com/thebkcircus/?hl=en')
,(83,'7183893809',NULL,'https://www.instagram.com/brothervellies/?hl=en')
,(84,NULL,NULL,'https://www.instagram.com/camerontea.jpg/')
,(85,NULL,NULL,'https://www.instagram.com/casamiraofficial/?hl=en')
,(86,NULL,NULL,'https://www.instagram.com/comebackasaflower/?hl=en')
,(87,NULL,NULL,'https://www.instagram.com/christopherjohnrogers/?hl=en')
,(88,NULL,NULL,'https://www.instagram.com/casualstudios/?hl=en')
,(89,NULL,NULL,'https://www.instagram.com/cushnie/')
,(90,NULL,NULL,'https://www.instagram.com/weardiop/?hl=en')
,(91,NULL,NULL,'https://www.instagram.com/__edas/?hl=en')
,(92,NULL,NULL,'https://www.instagram.com/flat.fifteen/')
,(93,NULL,NULL,'https://www.instagram.com/gizmo_vintage_honey/')
,(94,NULL,NULL,'https://www.instagram.com/goldengirlyshop/')
,(95,NULL,NULL,'https://www.instagram.com/houseofaama/?hl=en')
,(96,NULL,NULL,'https://www.instagram.com/kaicollective/?hl=en')
,(97,NULL,NULL,'https://www.instagram.com/kennethize/')
,(98,NULL,NULL,'https://www.instagram.com/kutula/?hl=en')
,(99,NULL,NULL,'https://www.instagram.com/laquan_smith/?hl=en')
,(100,NULL,NULL,'https://www.instagram.com/localeuropean/?hl=en')
,(101,'2122552811',NULL,'https://www.instagram.com/madamematovu/')
,(102,NULL,NULL,'https://www.instagram.com/maki.oh/?hl=en')
,(103,'7182439433',NULL,'https://www.instagram.com/moshoodofficial/?hl=en')
,(104,NULL,NULL,'https://www.instagram.com/nandi.naya/?hl=en')
,(105,NULL,NULL,'https://www.instagram.com/nudebarre/?hl=en')
,(106,NULL,NULL,'https://www.instagram.com/octave_jewelry/?hl=en')
,(107,NULL,NULL,'https://www.instagram.com/omathelabel/?hl=en')
,(108,NULL,NULL,'https://www.instagram.com/ovonion/?hl=en')
,(109,NULL,NULL,'https://www.instagram.com/orangecultureng/?hl=en')
,(110,NULL,NULL,'https://www.instagram.com/pejuobasa/?hl=en')
,(111,NULL,NULL,'https://www.instagram.com/postimperial/?hl=en')
,(112,NULL,NULL,'https://www.instagram.com/rebeccaallenny/?hl=en')
,(113,NULL,NULL,'https://www.instagram.com/riotswim/?hl=en')
,(114,NULL,'info@sincerelytommy.com','https://www.instagram.com/sincerelytommy_/?hl=en')
,(115,NULL,NULL,'https://www.instagram.com/thesixesnyc/?hl=en')
,(116,NULL,NULL,'https://www.instagram.com/slashedbytia/?hl=en')
,(117,NULL,NULL,'https://www.instagram.com/smallneeds/?hl=en')
,(118,NULL,NULL,'https://www.instagram.com/t.a.newyork/')
,(119,NULL,NULL,'https://www.instagram.com/telfarglobal/?hl=en')
,(120,NULL,NULL,'https://www.instagram.com/tlzlfemme/?hl=en')
,(121,NULL,NULL,'https://www.instagram.com/treefairfax/?hl=en')
,(122,NULL,NULL,'https://www.instagram.com/glemaud/?hl=en')
,(123,NULL,NULL,'https://www.instagram.com/walesbonner/?hl=en')
,(124,NULL,NULL,'https://www.instagram.com/yam_nyc/?hl=en')
,(125,NULL,NULL,'https://www.instagram.com/zouxoushoes/?hl=en')
,(126,NULL,NULL,'https://www.instagram.com/clueclothing/')
,(127,NULL,NULL,'https://www.instagram.com/adozencousins/?hl=en')
,(128,'9174727789',NULL,'https://www.instagram.com/alibiharlem/')
,(129,'9146546549','info@alvinandfriendsrestaurant.com','https://www.instagram.com/alvinandfriends/?hl=en')
,(130,NULL,NULL,'https://www.instagram.com/basbaassauce/?hl=en')
,(131,'2125107353','BeniamCuisine@gmail.com','https://www.instagram.com/benyam_cuisine/')
,(132,NULL,NULL,'https://www.instagram.com/blu_thebaker/')
,(133,'2126786200','info@boulevardbistrony.com','https://www.instagram.com/blvdbistro/')
,(134,NULL,NULL,'https://www.instagram.com/blkandbold/?hl=en')
,(135,'2126191200','info@brooklynchophouse.com','https://www.instagram.com/brooklynchophouse/')
,(136,'3472404281',NULL,'https://www.instagram.com/brooklyntea/?hl=en')
,(137,'2125860811','info@casadeltorony.com','https://www.instagram.com/casadeltorony/?hl=en')
,(138,'2122811800',NULL,'https://www.facebook.com/charlespanfried/')
,(139,'2122224545',NULL,'https://www.instagram.com/chocolatharlem/')
,(140,NULL,NULL,'https://www.instagram.com/cremasabsalon/?hl=en')
,(141,NULL,NULL,'https://www.instagram.com/globalvillagecuisine/?hl=en')
,(142,'6469983444',NULL,'https://www.instagram.com/harlemhops/')
,(143,NULL,NULL,'https://www.instagram.com/harvestandrevel/?hl=en')
,(144,'9143552527','JolosKitchen10@gmail.com','https://www.instagram.com/jolokitchen/')
,(145,NULL,NULL,'https://www.instagram.com/jonesbbqkc/?hl=en')
,(146,'3472819844',NULL,'https://www.instagram.com/juicesforlife/?hl=en')
,(147,NULL,NULL,'https://www.instagram.com/justiceofthepies/?hl=en')
,(148,NULL,NULL,'https://www.instagram.com/lilliesofchas/')
,(149,'6466493356',NULL,'https://www.instagram.com/lolosshacks/')
,(150,NULL,NULL,'https://www.instagram.com/maisonnoirwines/?hl=en')
,(151,NULL,NULL,'https://www.instagram.com/MikeyLikesItIceCream/')
,(152,NULL,NULL,'https://www.instagram.com/naturesingsnyc/')
,(153,'2124772804',NULL,'https://www.instagram.com/negrilvillagenyc/?hl=en')
,(154,NULL,NULL,'https://www.instagram.com/Onthehunt2006/')
,(155,NULL,NULL,'https://www.instagram.com/_evcooks/?hl=en')
,(156,'9146327373',NULL,'https://www.instagram.com/pepes_place/')
,(157,NULL,NULL,'https://www.instagram.com/redbaycoffee/?hl=en')
,(158,'9146657689','info@riperestaurant.com','https://www.instagram.com/ripekitchenbar/')
,(159,'9143652267',NULL,'https://www.instagram.com/rocnramen/')
,(160,NULL,NULL,'https://www.instagram.com/salutnutrition/?hl=en')
,(161,'2122220092',NULL,'https://www.instagram.com/seasonedvegan/?hl=en')
,(162,NULL,NULL,'https://www.instagram.com/theofficialsipsociety/')
,(163,NULL,NULL,'https://www.instagram.com/solcacao/')
,(164,'7186830482',NULL,'https://www.instagram.com/solsipsnyc/?hl=en')
,(165,NULL,NULL,'https://www.instagram.com/whetstonemagazine/?hl=en')
,(166,'6469280095',NULL,'https://www.instagram.com/tingsjamaicanjerkchicken/?hl=en')
,(167,NULL,NULL,'https://www.instagram.com/zafawines/')
,(168,NULL,'Pariss@BlackTechPipeline.com','https://www.instagram.com/btpipeline/')
,(169,NULL,NULL,'https://www.instagram.com/idontdoclubs/');

INSERT INTO addresses(address_id,street,city,state,zip,website) VALUES
 (1,NULL,NULL,NULL,NULL,'https://www.228grantstreet.com/')
,(2,NULL,NULL,NULL,NULL,'https://www.aphrochic.com/')
,(3,'623 Eagle Rock Ave Suite 124','West Orange','NJ','7052','https://www.theblackhome.com/')
,(4,NULL,NULL,NULL,NULL,'https://shopbppco.com/')
,(5,NULL,NULL,NULL,NULL,'https://boleroadtextiles.com/')
,(6,NULL,NULL,NULL,NULL,'https://www.clare.com/')
,(7,NULL,NULL,NULL,NULL,'https://www.claudehome.com/')
,(8,NULL,NULL,NULL,NULL,'https://effortlesscomposition.com/')
,(9,NULL,NULL,NULL,NULL,'https://www.goodeeworld.com/')
,(10,NULL,NULL,NULL,NULL,'https://www.ile-ila.com/')
,(11,NULL,NULL,NULL,NULL,'https://www.jungalow.com/')
,(12,'98 Moore Street','Brooklyn','NY','11206','https://www.lichennyc.com/')
,(13,'3199 Albany Post Rd, Suite 215','Buchanan','NY','10511','https://www.linoto.com/')
,(14,NULL,NULL,NULL,NULL,'https://www.litbklyn.co/get-lit')
,(15,NULL,NULL,NULL,NULL,'https://malenebarnett.com/shop')
,(16,NULL,NULL,NULL,NULL,'https://www.marieburgosdesignthestore.com/marie-burgos-collection-modern-furniture-home-decor')
,(17,'636 Washington Ave','Brooklyn','NY','11238','https://www.nattygarden.com/all-products')
,(18,NULL,NULL,NULL,NULL,'http://www.peaceandriot.com/shop')
,(19,NULL,NULL,NULL,NULL,'https://www.potterybyosa.com/')
,(20,'230 Park Avenue, 3rd fl-WEST','New York','NY','10169','https://robinwilsonhome.com/')
,(21,NULL,NULL,NULL,NULL,'http://www.rochelleporter.com/')
,(22,NULL,NULL,NULL,NULL,'https://seelineceramics.com/')
,(23,NULL,NULL,NULL,NULL,'https://www.sheilabridges.com/shop/')
,(24,NULL,NULL,NULL,NULL,'https://yoursustainablehome.com/')
,(25,'675 Ponce De Leon Ave NE N215','Atlanta','GA','30308','https://tackussanusenegal.com/')
,(26,NULL,NULL,NULL,NULL,'https://www.tactilematter.com/shop')
,(27,NULL,NULL,NULL,NULL,'http://www.osxnasozi.com/')
,(28,NULL,NULL,NULL,NULL,'https://www.shopyowie.com/')
,(29,NULL,'New York','NY',NULL,'https://www.eliaswilliams.com/')
,(30,NULL,'New York','NY',NULL,'https://elliottjeromebrownjr.com/')
,(31,NULL,'New York','NY',NULL,'http://www.joiriminaya.com/')
,(32,NULL,'New York','NY',NULL,'http://www.groanamelendez.com/')
,(33,NULL,'New York','NY',NULL,'https://www.mirandabarnes.com/')
,(34,NULL,NULL,NULL,NULL,'https://boldxchange.com/')
,(35,'115 North 7th Street','Brooklyn','NY','11249','https://celsious.com/')
,(36,'The Riverside Church, 91 Claremont Ave','New York','NY','10027','https://www.customcollaborative.org/')
,(37,NULL,NULL,NULL,NULL,'https://manualphoto.com/')
,(38,'1453 BEDFORD AVE','Brooklyn','NY','11216','https://www.marcheruedix.com/')
,(39,NULL,NULL,NULL,NULL,'https://neighborhoodfiberco.com/')
,(40,'4636 West Washington Blvd.','Los Angeles','CA','90016','https://rep.club/')
,(41,'54 7th Ave','Brooklyn','NY','11217','https://www.stringthingstudio.com/')
,(42,NULL,NULL,NULL,NULL,'http://beautystatcosmetics.com')
,(43,NULL,NULL,NULL,NULL,'http://beneathyourmask.com')
,(44,NULL,NULL,NULL,NULL,'http://blkgrn.com')
,(45,NULL,NULL,NULL,NULL,'http://briogeohair.com')
,(46,NULL,NULL,NULL,NULL,'http://golde.co')
,(47,NULL,NULL,NULL,NULL,'http://hanahanabeauty.com')
,(48,NULL,NULL,NULL,NULL,'http://hausurban.com')
,(49,NULL,NULL,NULL,NULL,'http://highbrowhippie.com')
,(50,NULL,NULL,NULL,NULL,'http://thehoneypot.co')
,(51,NULL,NULL,NULL,NULL,'http://gethyperskin.com')
,(52,NULL,NULL,NULL,NULL,'http://laurennapier.com')
,(53,NULL,NULL,NULL,NULL,'http://ouithepeople.com')
,(54,NULL,NULL,NULL,NULL,'https://www.patmcgrath.com/')
,(55,NULL,NULL,NULL,NULL,'https://www.peopleofcolorbeauty.com')
,(56,NULL,NULL,NULL,NULL,'https://unsuncosmetics.com')
,(57,NULL,NULL,NULL,NULL,'https://uomabeauty.com')
,(58,'3848 White Plains Rd','Bronx','NY','10467','https://zamboaroma.com')
,(59,'405 W 55th Street','New York','NY','10019','https://www.aileyextension.com/')
,(60,NULL,NULL,NULL,NULL,'https://blackgirlsrun.com/')
,(61,'47 W 14th St. 5th Floor','New York','NY','10011','https://www.bodyspacefitness.com/')
,(62,NULL,NULL,NULL,NULL,'https://www.grillzandgranola.com/')
,(63,'1082 Fulton Street','New York','NY','11238','https://www.healhaus.com/')
,(64,'210 5th Ave 5th Floor','New York','NY','10010','https://iconoclastfitness.com/')
,(65,NULL,NULL,NULL,NULL,'https://browse.theunderbelly.com/browse')
,(66,NULL,'Bronx','NY',NULL,'https://www.facebook.com/AndreaMindBodySoul/?ref=page_internal')
,(67,'724 Prospect Pl','Brooklyn','NY','11216','https://cafeconlibrosbk.com')
,(68,NULL,NULL,NULL,NULL,'https://frugalbookstore.net')
,(69,NULL,NULL,NULL,NULL,'https://harriettsbookshop.com')
,(70,NULL,NULL,NULL,NULL,'https://forkeepsbooks.com')
,(71,NULL,NULL,NULL,NULL,'https://fultonstreet918.com')
,(72,'131 Alexander Ave','Bronx','NY','10454','https://bookshop.org/shop/thelitbar')
,(73,NULL,NULL,NULL,NULL,'https://www.lovingmebooks.com/')
,(74,NULL,NULL,NULL,NULL,'https://www.mahoganybooks.com/')
,(75,NULL,NULL,NULL,NULL,'https://bookshop.org/shop/Semicolonchi')
,(76,'1942 Amsterdam Ave','New York','NY','10032','https://sistersuptownbookstore.com')
,(77,NULL,NULL,NULL,NULL,'https://www.instagram.com/sourceofknowledge/')
,(78,NULL,NULL,NULL,NULL,'https://anyalust.com/')
,(79,NULL,NULL,NULL,NULL,'https://babyphat.com/')
,(80,'287 Ralph Avenue','Brooklyn','NY','11233','https://www.bedstuyfly.com/')
,(81,NULL,NULL,NULL,NULL,'https://www.blkmktvintage.com/')
,(82,'150 Nevins St','Brooklyn','NY','11217','https://thebkcircus.com/')
,(83,'71 Franklin Street','Brooklyn','NY','11222','https://brothervellies.com/')
,(84,NULL,NULL,NULL,NULL,'https://www.instagram.com/camerontea.jpg/')
,(85,NULL,NULL,NULL,NULL,'https://www.castamira.com/')
,(86,NULL,NULL,NULL,NULL,'https://www.cbaaf.org/')
,(87,NULL,NULL,NULL,NULL,'https://www.instagram.com/christopherjohnrogers/?hl=en')
,(88,NULL,NULL,NULL,NULL,'https://www.coolandcasualstudios.com/')
,(89,NULL,NULL,NULL,NULL,'https://www.cushnie.com/')
,(90,NULL,NULL,NULL,NULL,'https://weardiop.com/')
,(91,NULL,NULL,NULL,NULL,'https://edas.store/')
,(92,NULL,NULL,NULL,NULL,'https://flatfifteen.co.uk/')
,(93,'438 Marcus Garvey Blvd','Brooklyn','NY','11216','https://www.instagram.com/gizmo_vintage_honey/')
,(94,NULL,NULL,NULL,NULL,'https://www.depop.com/goldengirlyshop/')
,(95,NULL,NULL,NULL,NULL,'https://houseofaama.com/')
,(96,NULL,NULL,NULL,NULL,'https://kaicollective.com/')
,(97,NULL,NULL,NULL,NULL,'https://www.instagram.com/kennethize/?hl=en')
,(98,NULL,NULL,NULL,NULL,'https://shopkutula.com/')
,(99,NULL,NULL,NULL,NULL,'https://laquansmith.com/')
,(100,NULL,NULL,NULL,NULL,'https://localeuropean.com/')
,(101,'240 West 10th Street','New York','NY','10014','https://www.instagram.com/madamematovu/')
,(102,NULL,NULL,NULL,NULL,'https://www.makioh.com/')
,(103,'1360 Fulton St','Brooklyn','NY','11216','https://afrikanspirit.com/')
,(104,NULL,NULL,NULL,NULL,'http://www.nandinayanyc.com/shop')
,(105,NULL,NULL,NULL,NULL,'https://nudebarre.com/')
,(106,NULL,NULL,NULL,NULL,'https://octavejewelry.com/')
,(107,NULL,NULL,NULL,NULL,'https://www.omathelabel.com/')
,(108,NULL,NULL,NULL,NULL,'https://www.whitneymero.com/')
,(109,NULL,NULL,NULL,NULL,'https://orangeculture.com.ng/')
,(110,NULL,NULL,NULL,NULL,'https://www.pejuobasa.com/')
,(111,NULL,NULL,NULL,NULL,'https://post-imperial.com/')
,(112,NULL,NULL,NULL,NULL,'https://rebecca-allen.com/')
,(113,NULL,NULL,NULL,NULL,'https://www.riotswim.com/')
,(114,'343 Tompkins Ave','Brooklyn','NY','11216','https://sincerelytommy.com/')
,(115,NULL,NULL,NULL,NULL,'https://www.thesixes.com/')
,(116,NULL,NULL,NULL,NULL,'https://www.slashedbytia.net/shop')
,(117,NULL,NULL,NULL,NULL,'Etsy: https://www.etsy.com/shop/RetroRhapsody')
,(118,'332 W 13th St','New York','NY','10014','https://shop-ta.com/')
,(119,NULL,NULL,NULL,NULL,'http://www.telfar.net/')
,(120,NULL,NULL,NULL,NULL,'https://www.tlzlf.com/')
,(121,NULL,NULL,NULL,NULL,'https://treefairfax.com/shop')
,(122,NULL,NULL,NULL,NULL,'https://www.glemaud.com/pages/home')
,(123,NULL,NULL,NULL,NULL,'https://walesbonner.net/')
,(124,NULL,NULL,NULL,NULL,'https://www.yamnyc.com/')
,(125,NULL,NULL,NULL,NULL,'https://www.zouxou.com/')
,(126,NULL,NULL,NULL,NULL,'https://clueclothings.com')
,(127,NULL,NULL,NULL,NULL,'https://adozencousins.com/')
,(128,'2376 Adam Clayton Powell Jr Blvd','New York','NY','10030','https://www.instagram.com/alibiharlem/')
,(129,'14 Memorial Hwy','New Rochelle','NY','10801','alvinandfriendsrestaurant.com')
,(130,NULL,NULL,NULL,NULL,'https://basbaassauce.com/')
,(131,'2795 Frederick Douglas Blvd','New York','NY','10039','http://benyamcuisine.com/')
,(132,NULL,NULL,NULL,NULL,'https://www.instagram.com/blu_thebaker/')
,(133,'2149 Frederick Douglass Blvd','New York','NY','10026','https://www.boulevardbistrony.com/')
,(134,NULL,NULL,NULL,NULL,'https://blkandbold.com/')
,(135,'150 Nassau St','New York','NY','10038','https://www.brooklynchophouse.com/')
,(136,'524 Nostrand Ave','Brooklyn','NY','11216','https://brooklyntea.com/')
,(137,'626B 10th ave,','New York','NY','10036','https://www.casadeltorony.com/home')
,(138,'2461 Frederick Douglass Blvd','New York','NY','10027','https://www.theinfatuation.com/new-york/reviews/charles-pan-fried-chicken')
,(139,'2223 Frederick Douglass Blvd','New York','NY','10026','https://www.chocolatharlem.com/')
,(140,NULL,NULL,NULL,NULL,'https://charlene-absalon-llc.square.site/')
,(141,NULL,NULL,NULL,NULL,'https://globalvillagecuisine.com/')
,(142,'2268 Adam Clayton Powell Jr Blvd','New York ','NY','10030','https://harlemhops.com/')
,(143,NULL,NULL,NULL,NULL,'http://harvestandrevel.com/')
,(144,'49 Lawton St','New Rochelle','NY','10801','jolosrestaurants.com')
,(145,NULL,NULL,NULL,NULL,'https://www.jonesbbqkc.com/')
,(146,'1026 Castle Hill Ave','Bronx','NY','10472','http://juicesforlife.nyc/')
,(147,NULL,NULL,NULL,NULL,'https://www.justiceofthepies.com/')
,(148,NULL,NULL,NULL,NULL,'https://www.lilliesofcharleston.com/')
,(149,'303 West 116th Street','New York','NY','10026','https://lolosseafoodshack.com/#about')
,(150,NULL,NULL,NULL,NULL,'https://maisonnoirwines.com/')
,(151,NULL,NULL,NULL,NULL,'https://mikeylikesiticecream.com/')
,(152,NULL,NULL,NULL,NULL,'https://www.etsy.com/shop/naturesingsnyc/')
,(153,'70 West 3rd St','New York','NY','10012','http://negrilnyc.com/')
,(154,NULL,NULL,NULL,NULL,'https://www.instagram.com/Onthehunt2006/')
,(155,NULL,NULL,NULL,NULL,'http://www.shopevelyncooke.com/')
,(156,'560 North Ave','New Rochelle','NY','10801','www.pepesplace.com')
,(157,NULL,NULL,NULL,NULL,'https://www.redbaycoffee.com/')
,(158,'151 W Sandford Boulevard','Mount Vernon','NY','10550','http://riperestaurant.com')
,(159,'19 Anderson St','New Rochelle','NY','10801','rocnramen914.com')
,(160,NULL,NULL,NULL,NULL,'https://salutnutrition.com/')
,(161,'55 ST. NICHOLAS AVENUE','New York','NY','10026','https://www.seasonedvegan.com/')
,(162,NULL,NULL,NULL,NULL,'https://www.thesipsociety.com/')
,(163,NULL,NULL,NULL,NULL,'https://www.solcacao.com/')
,(164,'203 Wilson Ave','Brooklyn','NY','11237','https://www.solsipsnyc.com/')
,(165,NULL,NULL,NULL,NULL,'https://www.whetstonemagazine.com/')
,(166,'75 9th Ave','New York','NY','10011','https://www.chelseamarket.com/directory-all/tings')
,(167,NULL,NULL,NULL,NULL,'https://zafawines.com/')
,(168,NULL,NULL,NULL,NULL,'https://www.blacktechpipeline.com/')
,(169,NULL,NULL,NULL,NULL,'https://idontdoclubs.com/');
